### ISSUE TITLE
Make it possible to send files to multiply receivers

### ISSUE THREAD

**Issue by Sopor** [trebleshot/android#100]
When I want to send a file to several devices I'm forced to select the file the same amount of times I want to send the file because I can't select the file and multi-select devices I want to send it to.

At the same time it should be possible to queue files to offline devices so when they get online it will automatically send the file I have queued.

**Comment by velitasali** [comment]
For the first one, have you tried `Add devices` option?

The second one makes sense.

**Comment by velitasali** [comment]
Closing the issue because you can expect the request as the default behavior and the second one as out of scope (it is hard to replicate on other platforms).
