### ISSUE TITLE
Website for Trebleshot - request

### ISSUE THREAD

**Issue by aha999** [trebleshot/android#111]
It would be nice to have a Trebleshot website so it would make a better visual representation of the project that could attract developers/contributors better and it would be easier for the general public than github itself.

A completely free and simple option is via Github Pages, that a lot of github open source projects are using, https://pages.github.com/
- Hosted directly from your GitHub repository. Just edit, push, and your changes are live.
- No databases are needed to be set up and no servers to configure

Examples of repos that use github pages: https://github.com/collections/github-pages-examples

Interesting article: https://www.toptal.com/github/unlimited-scale-web-hosting-github-pages-cloudflare

- Consider Jekyll. You give it Liquid templates and Markdown content
- Free Jekyll templates: https://jekyllthemes.io/free

**Comment by EzraEn1** [comment]
I volunteer as tribute! I'm willing to work on this issue.

**Comment by velitasali** [comment]
@EzraEn1 
> I volunteer as tribute! I'm willing to work on this issue.

Alright, I say let's do it. If you have any questions, please ask 😁

**Comment by ptanmay143** [comment]
Do you guys have any mock-ups as to how the website should look? Any ideas would help the one who is developing it.

**Comment by ptanmay143** [comment]
We can use a template for an app landing page to make the website making easier. I found a free template with the following license: "You can use all free and paid templates for an unlimited number of personal and commercial projects. The only limitation is that you can't offer for free or sell the templates as your own templates.". You can find the template at ( https://inovatik.com/leno-free-mobile-app-landing-page-template.html ). Using this template and making some changes, here is how it looks. Only a few changes were made so far. Except the copyright footer, we can change pretty much everything. I can do the changes as soon as I get the information to fill. Here is it: ( https://ptanmay143.github.io/trebleshot-website/ )

**Comment by ptanmay143** [comment]
If using templates is off the tables, I could try making one from scratch with the minimum information that is required for user visibility. What do you think?

**Comment by velitasali** [comment]
> Do you guys have any mock-ups as to how the website should look? Any ideas would help the one who is developing it.

The website is planned to be hosted on GitHub pages on https://github.com/trebleshot/trebleshot.github.io and @EzraEn1 volunteered to work on it and I am not sure if he is working locally. 

> We can use a template for an app landing page to make the website making easier. I found a free template with the following license: "You can use all free and paid templates for an unlimited number of personal and commercial projects. The only limitation is that you can't offer for free or sell the templates as your own templates.". You can find the template at ( https://inovatik.com/leno-free-mobile-app-landing-page-template.html ). Using this template and making some changes, here is how it looks. Only a few changes were made so far. Except the copyright footer, we can change pretty much everything. I can do the changes as soon as I get the information to fill. Here is it: ( https://ptanmay143.github.io/trebleshot-website/ )

The template looks nice. If it is a popular one, the colors may be altered a little. 

The main goal of the website is to tell about the project. 

The project FAQ https://github.com/genonbeta/TrebleShot/blob/master/FAQ.md can be used as a preliminary content. 

> If using templates is off the tables, I could try making one from scratch with the minimum information that is required for user visibility. What do you think?

I support anything that eases the development process, but this one should be asked to @EzraEn1. He may have created something already.

**Comment by EzraEn1** [comment]
Wow, I haven't checked this thread recently, this'll help a lot!

**Comment by ptanmay143** [comment]
> Wow, I haven't checked this thread recently, this'll help a lot! The template given is pretty cool, I was looking towards a variant of SinglePaged but if I could modify the app template to be more like a TrebleShot green style page, that would work great. Can't see the code right now, but will check in the morning.

This repo ( https://github.com/ptanmay143/trebleshot-website/ ) contains some of the changes that I did to the template like adding screenshots and features from Play Store description. As far as the color is concerned, it can be changed in the ./css/styles.css file. I think using the complete template should be avoided, as the licensing to the templates can change at any time. I'm not very sure about the licensing terms, so we should stay on the safer side. We could use this template as reference and build a website catering to our needs from scratch. We really don't need much features at the start, we could add them later.

**Comment by velitasali** [comment]
@ptanmay143 I pushed your changes to https://github.com/trebleshot/trebleshot.github.io.

**Comment by ptanmay143** [comment]
@velitasali I have made significant changes to the website and created a PR on [repo](https://github.com/trebleshot/trebleshot.github.io). The website contains almost little to no reference of the template app `Leno`.

Also, I have noticed that there are two separate GitHub repositories for the trebleshot (android) app. There are at https://github.com/genonbeta/TrebleShot and https://github.com/trebleshot/android respectively. I suppose this discussion on two different repositories if off-topic.

**Comment by velitasali** [comment]
@ptanmay143  https://github.com/trebleshot/android will be replaced with this repo. The Leno Template says the license is:

> You can use all free and premium templates for an unlimited number of personal and commercial projects. The only limitation is that you can't offer for free or sell the templates as your own templates.

which is not a license in my opinion. So, I can't say keeping only the copyright notice at the bottom is enough.

**Comment by ptanmay143** [comment]
I'm not sure what you mean by that. Personally I'm very new to software development in the real world, so the terms like licensing are very new to me. Hence, I suggest you review everything.
About the website, it is pretty much in its first beta stage. Maybe someone with good experience in web development could go through the repository and remove redundant javascript imports and css styles.
Working on this has given me a lot of experience in the git world as well as web development world. I would like to thank you for giving me the opportunity.

**Comment by velitasali** [comment]
> Working on this has given me a lot of experience in the git world as well as web development world. I would like to thank you for giving me the opportunity.

Thank you for taking the chance to work on this. Anything you learn will be a plus. 

> About the website, it is pretty much in its first beta stage. Maybe someone with good experience in web development could go through the repository and remove redundant javascript imports and css styles.

I can do that, but if you need time, you can take as much as you want. We are not in a hurry. If you think this can help you advance your coding skills and you have time, I'd be pleased to see you do that. 

> I'm not sure what you mean by that. Personally I'm very new to software development in the real world, so the terms like licensing are very new to me. Hence, I suggest you review everything.

The license provided by the creators of the template doesn't mention the ordinary, and that might be a problem. For instance, a good license would mention if attribution is needed and if so, where it should be put, etc. You said there is nothing left mentioning the original authors and I am not sure if that can be a problem with a license like that.

**Comment by ptanmay143** [comment]
> The license provided by the creators of the template doesn't mention the ordinary, and that might be a problem. For instance, a good license would mention if attribution is needed and if so, where it should be put, etc. You said there is nothing left mentioning the original authors and I am not sure if that can be a problem with a license like that.
Oh, I get it now. I didn't mean that there is nothing left mentioning the original authors. The credits are there in all the files. I just meant that, initially the template was made for an application named Leno, and now there is no mention of Leno anywhere. By anywhere I mean on the front-end side atleast. This means that the website now totally focuses on the app Trebleshot while giving credits to the original template designer/author.

**Comment by velitasali** [comment]
>By anywhere I mean on the front-end side atleast. This means that the website now totally focuses on the app Trebleshot while giving credits to the original template designer/author.

I see. Thanks for explaining :)

**Comment by mubashir-rehman** [comment]
This issue should be closed as it seems to be resolved.

**Comment by velitasali** [comment]
Thanks for the reminder.
