### ISSUE TITLE
Transforming to Kotlin & Embracing testing

### ISSUE THREAD

**Issue by velitasali** [trebleshot/android#119]
The project is in dire of quick testing and the ability to code faster with less error & with great support. The speed and support side can be achieved if we transform to Kotlin given now it is now a first-class citizen in Android development.

**When resolved, this will deliver:**
1- Code in **Kotlin** for greater support of the platform
2- Testing to accelerate the development process
3- [Knowledge](https://youtu.be/jksPhQhJRoc)

**How are we going to transform?**
Simple, we just adopt the arch components and drop custom libraries like [GDatabase](https://github.com/genonbeta/GDatabase) for [Room](https://developer.android.com/topic/libraries/architecture/room?gclid=Cj0KCQjwzN71BRCOARIsAF8pjfgNKGeJn3GT8HzgjUiOplFG87azaC6eQJXvINk8O_xhNuczbIysIaQaAlRaEALw_wcB&gclsrc=aw.ds) and probably most of the classes of [framework-android](https://github.com/genonbeta/framework-android). This will take some time because the test cases will need to be written to complete the process.

**What is missing?**
[Knowledge](https://youtu.be/jksPhQhJRoc) & test cases.

*This thread will be updated as more data is available.*

**Comment by ashirmehmood1996** [comment]
it will be great.
