### ISSUE TITLE
Long press on tile should take us to the app

### ISSUE THREAD

**Issue by Antiscl** [trebleshot/android#120]
Whenever we long press on the tile ( notification panel > share files) it takes to the app settings ( system settings).
I think it would be more useful if it take us to the app itself.
 Hope you understood and thank you for the app!

**Comment by yashj6294** [comment]
Hello I would like to work on this issue. Can you please assign this issue to me

**Comment by velitasali** [comment]
@yashj6294 Thanks! Please use the latest source code from the `master` branch.

**Comment by yashj6294** [comment]
I would like to know where your community of developers interact
So in future if I face any problem then I can get it cleared over there
