### ISSUE TITLE
device serial

### ISSUE THREAD

**Issue by viskum** [trebleshot/android#129]
Hey...Developer...
Thanks for making this wonderful application open source...
I really liked it....
I just want to ask you when i am debugging this application i an getting this type of error in android 10 device
Caused by: java.lang.SecurityException: getSerial: The user 10214 does not meet the requirements to access device identifiers.
I also tested this on marshmallow device but it is working fine...
please tell me how to fix this issue...

**Comment by velitasali** [comment]
Next versions will not be using device serials as identifiers. In other words, I already fixed this issue.
