### ISSUE TITLE
Need of compress (folder) into ZIP, providing sort by TYPE And select by TYPE in file explorer. 

### ISSUE THREAD

**Issue by Rakesh00100** [trebleshot/android#132]
Allowing the features 

1 Sort by type and select all by type
2 Compress (folder) into zip [Just like Amaze file manager as Team amaze is providing] 

are really good features needed in File explorer section for all time one app use.

**Comment by mubashir-rehman** [comment]
This can be achieved by adding an option to use system file picker or other file mangers for the time being.

**Comment by velitasali** [comment]
These are very generic features that are out of the scope of a file-transfer application. You can ZIP using another file manager. 

Anyway, I will not close this issue for the being as I might work the ZIP feature. The other two are unlikely, though.
