### ISSUE TITLE
Failed to connect  as receiver on android 10.

### ISSUE THREAD

**Issue by aashitshah26** [trebleshot/android#139]
First of all thank you for such a great library. The bug appears only on devices running android 10 . They cant connect to the created hotspot in other device.

1. Create a hotspot in device 1 and send file.
2.  In device 2 (with android 10) click on receive and scan qr code.
3. Connection will time out

The error occuring is :
 Ping fails to the scanned device.

**Comment by beNitinhere** [comment]
@aashitshah26 Any update?

**Comment by aashitshah26** [comment]
@beNitinhere  This happens when the receiver  runs on android 10 and has mobile data enabled . Disabling mobile data solved the problem . But the whole transfer breaks when we build the project with targetSdk 29 might be due some security changes starting from android Q.

**Comment by ahmadarslan13** [comment]
Got the same issue not helped on targetsdk 29

**Comment by kishansinghpanwar** [comment]
Any update on this issue ?

**Comment by velitasali** [comment]
The currently visible codebase is out of date. I will release the codebase along with the new version. This was a precaution taken due to some events that occurred in May 2020

**Comment by mjbdl** [comment]
> First of all thank you for such a great library. The bug appears only on devices running android 10 . They cant connect to the created hotspot in other device.
> 
> Steps to reproduce the behavior:
> 
> 1. Create a hotspot in device 1 and send file.
> 2. In device 2 (with android 10) click on receive and scan qr code.
> 3. Connection will time out
> 
> The error occuring is :
> Ping fails to the scanned device.

Use pro version of Trebleshot
With many features.

https://github.com/Shiv-Shambhu/Leaf-Explorer

**Comment by mjbdl** [comment]
> First of all thank you for such a great library. The bug appears only on devices running android 10 . They cant connect to the created hotspot in other device.
> 
> Steps to reproduce the behavior:
> 
> 1. Create a hotspot in device 1 and send file.
> 2. In device 2 (with android 10) click on receive and scan qr code.
> 3. Connection will time out
> 
> The error occuring is :
> Ping fails to the scanned device.

Use pro version of Trebleshot
With many features.

https://github.com/Shiv-Shambhu/Leaf-Explorer

**Comment by kishansinghpanwar** [comment]
@mjbdl, I want to let you know we are talking here about the Issue/Bug of this code, not about purchase or use of another library or code. 
And second thing, decide first whether you are selling that code or it's just open source, because you're using the term "donate" in your dummy repo for purchase code instead of "Buy/Purchase" Correct this first. 

And please do not advertise like this for any issue in other repo. 
Thanks

**Comment by velitasali** [comment]
See https://github.com/trebleshot/android/issues/161#issuecomment-894015203

I will also add the invalid tag to this issue because it is hard to understand what causes the issue (Android or the app's implementation). It would have been better if it had the logs as well.
