### ISSUE TITLE
Can we upload this clone app to playstore 

### ISSUE THREAD

**Issue by Nikhil27b** [trebleshot/android#142]
So we can clone and use this app and upload to playstore without credits because someone clone this app and uploaded on playstore without any credits 
[App link ](https://play.google.com/store/apps/details?id=go.dodo.GETit) 
 https://play.google.com/store/apps/details?id=go.dodo.GETit

**Comment by SweetD3v** [comment]
Nope. Don't be fooled by that. This project has the GPL 2.0 license. So you have to follow all the legal terms & conditions of it.
This is open source project but it has its regulations.
If you are cloning this project, then you must give the credits to its original developers within your app or within the playstore app description as well as, You have to give free access to your modified code to all developers.
You can check more details about the GPL 2.0 license on main page or just google it.

**Comment by Nikhil27b** [comment]
So why this user clone and upload app to playstore with credits and license

**Comment by nivranaitsirhc** [comment]
@velitasali did you sell Trebleshot?
Somebody might be profiting from your work, I read the app and reviews they are claiming "Dodo Drop - Secure File Transfer (Made in India)"

**Comment by Nikhil27b** [comment]
![Screenshot_20200804-195457_Google Play Store](https://user-images.githubusercontent.com/45140298/89305903-d5dcbc00-d68c-11ea-83d6-33fb117731a2.jpg)
How this app is trending 4 in india and still made a money from that @velitasali

**Comment by nivranaitsirhc** [comment]
The spike is caused by media outlets in India phrasing the app made by a 17 years old boy. Its riding the feud between China apps and India apps. 
With the "Made in India" slogan it has caught the patriotism of the country and probably does not care if its somebody's hard earned work.

**Comment by ashirmehmood1996** [comment]
Take a closes look at this [link](https://codecanyon.net/item/turbo-share-shareit-clone-transfer-share-popular-app-admob-onesignal-integration/24505829) may be some one has already made a number of sales on codecanyon already.

**Comment by LittleWhole** [comment]
I saw this app too. I can't believe someone just entirely copied TrebleShot and uploaded it to the play store.

**Comment by velitasali** [comment]
This question already has an answer in the license file. Please refer to it for this kind of question.
