### ISSUE TITLE
Removal of Hotspot Features

### ISSUE THREAD

**Issue by velitasali** [trebleshot/android#144]
Even though it is a neat feature to have when it works, QR Code and hotspot (or WiFi connection in particular) features are a headache to implement. It may be better for the user to remove those altogether given that with each Android release, it becomes harder to work with them 

Also, there are privacy concerns. Location permission and other revealing parts of the Android System have to be in use for these to work which is not a great sign for the uninformed users. 

I am more interested in making TrebleShot (uprotocol) widely available than giving all the attention to Android development.

WiFi Direct will likely to supersede these features.

**Comment by ashirmehmood1996** [comment]
will wifi direct be able to support all the android devices?

**Comment by velitasali** [comment]
Whether it does or not, it will be easier to work with. Most people don't care about the effort. They want the app to just work. To make it so and not to take all the blame when it doesn't work, this is the right choice.

When QR Code doesn't work, they can blame it on us (because of the implemention).But if WiFi Direct doesn't work, we can blame the hardware. 

Also, QR Code feature is taking too much time to test.

To be honest, they are many reasons to avoid working with it.

**Comment by mubashir-rehman** [comment]
That's a pretty a good decision to make. However, I would suggest adding something like this in advanced settings or better a separate package (like extensions) that would install as an app and only provide functionality (as currently implemented).
Also, that is just a suggestion. If that requires some work, then can be left for future implementation.
If you suggest, I will make an issue for that(support for extension).

**Comment by velitasali** [comment]
I am not into making things complicated, but if you can come up with a good
plan, maybe we can think about extensions.

**Comment by vairag22** [comment]
Shouldn't both options be available? Personally, I have found WiFi Direct is slower than Hotspot.

**Comment by vairag22** [comment]
> Even though it is a neat feature to have when it works, QR Code and hotspot (or WiFi connection in particular) features are a headache to implement. It may be better for the user to remove those altogether given that with each Android release, it becomes harder to work with them
> 
> Also, there are privacy concerns. Location permission and other revealing parts of the Android System have to be in use for these to work which is not a great sign for the uninformed users.
> 
> I am more interested in making TrebleShot (uprotocol) widely available than giving all the attention to Android development.
> 
> WiFi Direct will likely to supersede these features.

How will it affect the transfer speeds? I found WiFi Direct to be very slow, maybe it was improper implementation. Nevertheless, hotspot is very fast.

**Comment by velitasali** [comment]
It shouldn't affect it as long as the bandwidth is spared for WiFi Direct, meaning you shouldn't be connected to a WiFi network.

**Comment by velitasali** [comment]
It looks like the WiFi Direct feature will need `ACCESS_FINE_LOCATION` permission which will require the user to enable full location permission in order for this to work.

**Comment by velitasali** [comment]
False alarm. We are already using fine location permission :smile:
