### ISSUE TITLE
Receive/ Reject accidents

### ISSUE THREAD

**Issue by poppypundit** [trebleshot/android#145]
The notification intimating a transfer request is Receive/Reject. I can't explain the amount of times I've accidentally pressed Reject. Can it be changed to Accept/Reject? Also I'm not sure if it's usually Accept/Reject or Reject/Accept. 

I hope its not a petty complaint. 🙏

**Comment by velitasali** [comment]
I am not sure what is causing the issue here. Is it the order of the buttons or the way they were named?

**Comment by ildar** [comment]
This is a trouble with UX.

**Comment by poppypundit** [comment]
I always happen to click reject vs receive. I'm guessing it is the order of the buttons. But I also think both beginning with letter R can also  quickly cause confusion. I do agree it is a very minor ( petty) complaint when there are more worrying concerns in this world. 

I think the right button is "YES" and left button is "NO" for the UI in general. I might be wrong. Images attached. 


![IMG_20200917_093058](https://user-images.githubusercontent.com/18294483/93444478-8d89fe00-f8c8-11ea-80ea-f46d358514e3.jpg)
![IMG_20200917_092302](https://user-images.githubusercontent.com/18294483/93444479-8e229480-f8c8-11ea-83ba-d197a4583d10.jpg)
![IMG_20200917_092231](https://user-images.githubusercontent.com/18294483/93444481-8ebb2b00-f8c8-11ea-89c4-4a79d82f5bf2.jpg)

**Comment by velitasali** [comment]
I see. You are not wrong. I should have used an antonym for that. 

Thanks for the suggestion :+1:
