### ISSUE TITLE
After QR scann the device is not adding 

### ISSUE THREAD

**Issue by safeeraliPS** [trebleshot/android#150]
After QR scann the file sending page show pending and on top it shows the divise is not add how to resolve the issue were can I find the code for device connect and I need to fix the issue

**Comment by safeeraliPS** [comment]
![Screenshot_20201101_121246](https://user-images.githubusercontent.com/65153590/97796728-af063580-1c3b-11eb-9425-3446e0ae1aab.jpg)

**Comment by safeeraliPS** [comment]
![Uploading IMG_20201101_121522.jpg…]()

**Comment by safeeraliPS** [comment]
![Uploading IMG_20201101_121522.jpg…]()

**Comment by safeeraliPS** [comment]
![IMG_20201101_121522](https://user-images.githubusercontent.com/65153590/97796769-3f447a80-1c3c-11eb-8415-34ecf27dce87.jpg)

**Comment by velitasali** [comment]
Does the QR code scanner exit with an error? If not, please provide the logs for this problem.

**Comment by safeeraliPS** [comment]
No irror in QR scanner and log also show no irror QR Code scanner working properly after scan it's not working no issue in log also

**Comment by safeeraliPS** [comment]
I will send the project code to you can you check it please send me your email

**Comment by velitasali** [comment]
Is this your own build? If so, please know that, unless you open a merge request, I cannot help you. 

If you need paid assistance, please send an email to the address in my profile.

**Looking at the screenshot, it looks like this is a custom build and for that reason, I am closing this issue.**
