### ISSUE TITLE
targetSdkVersion 30 to not working creating hotspot and wifi.

### ISSUE THREAD

**Issue by Ankitinnovatree** [trebleshot/android#154]
gradle  to change targetSdkVersion 30 not working creating hotspot and wifi. 

phone/mobile version
android version 10

**Comment by poorvajappja** [comment]
Can you give more information ?

**Comment by poorvajappja** [comment]
I am  also using android version 10. It works smoothly for me .

Can  you give more information ?

**Comment by Ankitinnovatree** [comment]
i have change targetsdkversion library version 28 and i am change 28 to 30 .

and issue is Samsung  mobile android version 10 to not creating hotspot and i am creating manually to hotspotmanagerfragment only show stop hotspot and qr code not showing.

**Comment by poorvajappja** [comment]
Can you give the screen shot ?

**Comment by poorvajappja** [comment]
Send the screen shot

**Comment by aqeelzoobi** [comment]
@Ankitinnovatree  did u find any solution to connect in Android 10 with target sdk 30 ?

**Comment by Ankitinnovatree** [comment]
sorry , but no found any solution's.

**Comment by velitasali** [comment]
Without making the appropriate changes, just increasing the SDK level will cause more problems. You should get rid of any deprecated APIs if you want to support newer versions of Android.

**Comment by aqeelzoobi** [comment]
> Without making the appropriate changes, just increasing the SDK level will cause more problems. You should get rid of any deprecated APIs if you want to support newer versions of Android.

I resolved all other bugs successfully, it just doing issue to connect the hotspot in android 10,
its receiving files in Android 10 but its doing issue when sending file. and issue is to connect with the user hotspot.

**Comment by sergemastaki** [comment]
@aqeelzoobi That issue may be caused by change in android 10 api. Apps are not allowed to activate wifi programmatically.

**Comment by aqeelzoobi** [comment]
@sergemastaki  @velitasali . Dear thanks for response. i resolved the issue and connect the wifi in android 10.

**Comment by aqeelzoobi** [comment]
> @aqeelzoobi That issue may be caused by change in android 10 api. Apps are not allowed to activate wifi programmatically.

Yes its because of android 10. U can connect wifi in android 10 using WifiNetworkSpecifier.
https://developer.android.com/reference/android/net/wifi/WifiNetworkSpecifier.Builder

**Comment by mjbdl** [comment]
> gradle to change targetSdkVersion 30 not working creating hotspot and wifi.
> 
> phone/mobile version
> android version 10

Use pro version of Trebleshot
With many features.

https://github.com/Shiv-Shambhu/Leaf-Explorer
