### ISSUE TITLE
Connection Error:  When selected more than 500 MB

### ISSUE THREAD

**Issue by aqeelzoobi** [trebleshot/android#157]
Many time in android connection will failed when select files more than 20 or above, when total size will increase its will through the connection between the transaction.

**Comment by mubashir-rehman** [comment]
Thanks for reporting the issue. However, logs might help a lot and can be taken with adb logcat or in app "Contact and Feedback" button from the side bar.

**Comment by aqeelzoobi** [comment]
if (!inetAddress.isReachable(1000))
                throw new IOException("Ping test before connection to the address has failed");
its through ping test exception. when transfer files from android 10 to 10

**Comment by mjbdl** [comment]
Use pro version of Trebleshot
With many features.

https://github.com/Shiv-Shambhu/Leaf-Explorer

**Comment by mjbdl** [comment]
> if (!inetAddress.isReachable(1000))
> throw new IOException("Ping test before connection to the address has failed");
> its through ping test exception. when transfer files from android 10 to 10

Use pro version of Trebleshot
With many features.

https://github.com/Shiv-Shambhu/Leaf-Explorer
