### ISSUE TITLE
protocol: Fails due to lack of network switching

### ISSUE THREAD

**Issue by vandanabpatel** [trebleshot/android#161]
error while i try to connect using IP address
client.setSecureKey(accessPin);
CoolSocket.ActiveConnection activeConnection = client.connectWithHandshake(ipAddress, false);

////////////////////// here i attach log 

E/ConnectionUtils: establishHotspotConnection(): Waiting to connect to the server
E/ConnectionUtils: establishHotspotConnection(): No DHCP provided. Looping...
E/ConnectionUtils: establishHotspotConnection(): Waiting to connect to the server
E/ConnectionUtils: establishHotspotConnection(): No DHCP provided. Looping...
E/ConnectionUtils: establishHotspotConnection(): Waiting to connect to the server
E/ConnectionUtils: establishHotspotConnection(): DhcpInfo: gateway: 192.168.0.1 dns1: 192.168.0.1 dns2: 0.0.0.0 ipAddr: 192.168.0.65 serverAddr: 192.168.0.1 netMask: 0.0.0.0
E/ConnectionUtils: establishHotspotConnection(): There is DHCP info provided waiting to reach the address 192.168.0.1
E/ConnectionUtils: establishHotspotConnection(): AP has been reached. Returning OK state.
E/UIConnectionUtils: ipAddress::192.168.0.1
E/UIConnectionUtils: accessPin::1617340335
W/System.err: java.net.ConnectException: failed to connect to /192.168.0.1 (port 1129) from /:: (port 54967): connect failed: ECONNREFUSED (Connection refused)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:142)
W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
W/System.err:     at java.net.Socket.connect(Socket.java:621)
W/System.err:     at java.net.Socket.connect(Socket.java:570)
W/System.err:     at com.genonbeta.CoolSocket.CoolSocket$ActiveConnection.connect(CoolSocket.java:516)
W/System.err:     at com.genonbeta.CoolSocket.CoolSocket$Client.connect(CoolSocket.java:804)
W/System.err:     at com.android.connection.CommunicationBridge$Client.connect(CommunicationBridge.java:87)
W/System.err:     at com.android.connection.CommunicationBridge$Client.connectWithHandshake(CommunicationBridge.java:95)
W/System.err:     at com.android.connection.UIConnectionUtils$4.onConnect(UIConnectionUtils.java:203)
W/System.err:     at com.android.connection.CommunicationBridge.connect(CommunicationBridge.java:46)
W/System.err:     at com.android.connection.CommunicationBridge.connect(CommunicationBridge.java:35)
W/System.err:     at com.android.connection.UIConnectionUtils.setupConnection(UIConnectionUtils.java:197)
W/System.err:     at com.android.connection.UIConnectionUtils$3.onRun(UIConnectionUtils.java:124)
W/System.err:     at com.android.connection.InterruptAwareJob.run(InterruptAwareJob.java:13)
W/System.err:     at com.android.service.WorkerService$RunningTask.run(WorkerService.java:330)
W/System.err:     at com.android.service.WorkerService$1.run(WorkerService.java:180)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
W/System.err: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
W/System.err:     at libcore.io.Linux.connect(Native Method)
W/System.err:     at libcore.io.ForwardingOs.connect(ForwardingOs.java:94)
W/System.err:     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:138)
W/System.err:     at libcore.io.ForwardingOs.connect(ForwardingOs.java:94)
W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:156)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:134)
W/System.err: 	... 24 more

**Comment by velitasali** [comment]
I consider this issue fixed as the app now has network switching, allowing it to target Wi-Fi or ethernet when connecting to other devices.
