### ISSUE TITLE
Request for possible future update

### ISSUE THREAD

**Issue by ghost** [trebleshot/android#164]
This is a request regarding a possible future update.
Can you add the following features:
1. Executable (.exe) file for TrebleShot PC Setup
2. Dark mode or a customisable UI
3. Receive button in browser
4. Browsing and selecting what files to receive option: If the Share via Browser option is selected let the person select files manually from the other devices as in the alternative given( WiFi File Transfer ).
5. Static/ Custom IP with Custom Port ( I don't know how IP works so you can tell  if this is not possible )

Alternatives: 
1. WiFi File Transfer by smarterDroid
( https://play.google.com/store/apps/details?id=com.smarterdroid.wififiletransfer )

2. Sweech by Èric ALBER
https://play.google.com/store/apps/details?id=com.sweech

Thanks in advance

**Comment by velitasali** [comment]
(Closing as the request is no longer valid.)
