### ISSUE TITLE
Make a tag to allow new versions to be present in F-droid

### ISSUE THREAD

**Issue by proletarius101** [trebleshot/android#166]
**Is your feature request related to a problem? Please describe.**
TrebleShot hasn't released a new tag since 2019, although it's still actively maintained. However, only git tags trigger builds on fdroid. So the fdroid TrebleShot is still the 2019 one.

**Describe the solution you'd like**
Make a new git tag to update the versions on F-droid.

**Comment by velitasali** [comment]
I am aware of that. 

I haven't released it because It is not ready.

**Comment by velitasali** [comment]
A new version is now available!
