### ISSUE TITLE
Permission changed for API startLocalOnlyHotspot but is neither declared nor checked

### ISSUE THREAD

**Issue by wowhhh** [trebleshot/android#174]
Hi, there, I've found an issue in version **1.4.2**, which is downloaded from [F-Droid](https://f-droid.org/packages/com.genonbeta.TrebleShot/).

### Describe the bug
I found the usage of `startLocalOnlyHotspot` may cause compatibility bugs. It is related to the call chain:

```
com.genonbeta.TrebleShot.service.CommunicationService.onStartCommand(android.content.Intent,int,int)int
 com.genonbeta.TrebleShot.service.CommunicationService.setupHotspot()void
  com.genonbeta.TrebleShot.util.HotspotUtils$OreoAPI.enableConfigured(java.lang.String,java.lang.String)boolean
   com.genonbeta.TrebleShot.util.HotspotUtils$OreoAPI.enable()boolean
    android.net.wifi.WifiManager.startLocalOnlyHotspot(android.net.wifi.WifiManager$LocalOnlyHotspotCallback,android.os.Handler)void
```

This API needs `ACCESS_COARSE_LOCATION` permission at [API-level 28](https://android.googlesource.com/platform/frameworks/base/+/pie-dev/wifi/java/android/net/wifi/WifiManager.java#1979) and below, but is changed to `ACCESS_FINE_LOCATION` in [29](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android10-dev/wifi/java/android/net/wifi/WifiManager.java#2630). The app only uses **coarse location** in the manifest.

-----
**In API 28**
![b826421f9cf4aa117ab6f3b57e3c4b9](https://user-images.githubusercontent.com/26241319/127765745-afae2468-2f8d-4903-baba-94ba85dc28fc.png)

---
**In API 29**
![ac6da51ea53516c62567df6afd85d6b](https://user-images.githubusercontent.com/26241319/127765753-df06ca21-5692-4d8c-8f12-a888ea43bce8.png)

---
It can be fixed by adding **fine location** to the manifest, and request for the **fine location** at somewhere in the program (maybe before calling that API, and also check `SDK_INT>28`).

I found only the **coarse location** permission is there when I start a hotspot (through ADB).
![image](https://user-images.githubusercontent.com/26241319/127765530-2b18973d-eeb1-4442-85ae-a155f47059e9.png)

Can you help me review this issue? @velitasali 
Thanks !!!

**Comment by velitasali** [comment]
Thanks for the thorough description. 

The changes you are suggesting are already there in the latest revision. 

https://github.com/trebleshot/android/blob/b62716f1c4789df16cf3c3c811f88f58c593dde4/app/src/main/AndroidManifest.xml#L24

https://github.com/trebleshot/android/blob/b62716f1c4789df16cf3c3c811f88f58c593dde4/app/src/main/java/org/monora/uprotocol/client/android/util/HotspotManager.kt#L86

https://github.com/trebleshot/android/blob/b62716f1c4789df16cf3c3c811f88f58c593dde4/app/src/main/java/org/monora/uprotocol/client/android/util/Connections.kt#L174

**Comment by wowhhh** [comment]
> Thanks for the thorough description.
> 
> The changes you are suggesting are already there in the latest revision.
> 
> https://github.com/trebleshot/android/blob/b62716f1c4789df16cf3c3c811f88f58c593dde4/app/src/main/AndroidManifest.xml#L24
> 
> https://github.com/trebleshot/android/blob/b62716f1c4789df16cf3c3c811f88f58c593dde4/app/src/main/java/org/monora/uprotocol/client/android/util/HotspotManager.kt#L86
> 
> https://github.com/trebleshot/android/blob/b62716f1c4789df16cf3c3c811f88f58c593dde4/app/src/main/java/org/monora/uprotocol/client/android/util/Connections.kt#L174

Awesome! Very thanks!
