### ISSUE TITLE
jpg, png, svg file is not able to open from catch folder

### ISSUE THREAD

**Issue by Jackykabra123** [trebleshot/android#177]
Hello sir,

Now i am trying to share all file like ( jpg, png, mp3, wav and etc)

I sent file and getting successfully but images files not able to open and getting error in device like (Can't able to open this file type).

I have also solution can you please set extention when save images file may be solve this issue so please check and let me know after solove it.

**Comment by velitasali** [comment]
* Which version of the app?
* Can you provide a screen recording or the logs?

Please use the appropriate template before filing an issue next time.

**Comment by Jackykabra123** [comment]
- Android 10 Device: Motorola power one
- Yes please check below link.

**Comment by Jackykabra123** [comment]
- Android 10 Device: Motorola power one
- Yes please check below link.

https://user-images.githubusercontent.com/49706999/128026339-16e604d7-7abd-466e-9beb-c6b366006edd.mp4

**Comment by velitasali** [comment]
Thanks for trying it out, but please don't report bugs regarding an unreleased version of the app. What you are seeing is an unimplemented part of the software. 

:v:

**Comment by Jackykabra123** [comment]
Can you please let know when we wants to get receive file to view or preview?
