### ISSUE TITLE
WIP: release: 2.0

### ISSUE THREAD

**Issue by velitasali** [trebleshot/android#178]
### First Alpha 

- [x] Ability to open files in the app (https://github.com/trebleshot/android/commit/1d50f4e1bed99486f64c2dff374651e5ce1208b7)
- [x] Implement _Manage Devices_ (https://github.com/trebleshot/android/commit/e119d736da1acf2cebca74e3f184b6b1fb3f4eac)
- [x] _Preferences_ and _Manage Devices_ should be destinations in `nav_home` (https://github.com/trebleshot/android/commit/e119d736da1acf2cebca74e3f184b6b1fb3f4eac)

### Second Alpha

- [x] Ensure versions below API 21 are functioning (https://github.com/trebleshot/android/commit/0b495e6606fc97f30f1fb79af05a717d5f4ee946)
- [x] Fix uprotocol TLSv1 issue (only TLSv1.2 works right now) (https://github.com/trebleshot/android/commit/0b495e6606fc97f30f1fb79af05a717d5f4ee946)
- [x] Implement uprotocol's revoke certificates feature (https://github.com/trebleshot/android/commit/510aaebe141b0ae8ecb4d77bd359f3b25f084c6c)
- [x] Change save destination (https://github.com/trebleshot/android/commit/b065a8c6a7e4c1c1c79cbe872415c49807b5aed3)
- [x] Emphasize that the app uses uprotocol (https://github.com/trebleshot/android/commit/067a988d3f4d2384fac72c69f8c796eb601dc9f0)
- [x] Ability to edit selections in content (https://github.com/trebleshot/android/commit/d77d841f3c634e0f71a1ae8a37b684d35e264e82)
- [x] Group by categories in Music, Image, Video sections using https://material.io/components/chips#input-chips (https://github.com/trebleshot/android/commit/6ce2bc9f7929841a7ea4e41979ea038c24350c14, https://github.com/trebleshot/android/commit/6ec5ff6e7aba96770a3eb6694f9574b9057976d2)

### Release (First beta)

- [x] Web Share when shared through other apps (`ACTION_SEND`, `ACTION_SEND_MULTIPLE`) (https://github.com/trebleshot/android/commit/307fa575158cda60f9255db3a7e306af8f6d9b40)
- [x] Refactor strings (remove unused ones and drop the use of prefixes) (https://github.com/trebleshot/android/commit/76e50d41f88f30a3c7bc06dc8c42e203e0576653)
- [x] API 29 Package Installer (https://github.com/trebleshot/android/commit/dd5e1be02bd992bd541a7f0a4ec71c6fdc5dc10a)

## Additional (may skip for 2.0)

- [ ] Ability to delete and rename contents
- [ ] _Try to_ re-enable failure on linting errors (currently disabled)
- [ ] Ability to change the save directory of a transfer (move the contents (received or being received but not running))
- [ ] Filtering (content specific)
- [ ] Ability to select section titles (selects the contents under it)

## Low priority (doesn't improve the experience)

- [ ] App-wide search

**Comment by mubashir-rehman** [comment]
If trebleshot uses jetpack compose, then chips isn't available yet.
![image](https://user-images.githubusercontent.com/51048830/128440249-f06bc147-dd64-44b4-90b6-428891a27738.png)

**Comment by velitasali** [comment]
@mubashir-rehman No, jetpack-compose doesn't support below Android 23, so this project doesn't use it :)
