### ISSUE TITLE
Dependent features configured but no package ID was set when trying to run app module

### ISSUE THREAD

**Issue by UltraBurstXD** [trebleshot/android#179]
Hi,

I'm getting '**Dependent features configured but no package ID was set**' error, when trying to run the 'app' project module. My project and the main project (Trebleshot) are nearly the same... Is there any workaround?

**Comment by velitasali** [comment]
The information you provided is insufficient to understand the problem. Also, you already said it is unrelated to TrebleShot, so closing this!

**Comment by UltraBurstXD** [comment]
I didn't say it was unrelated, but little different because I excluded some functions. I'm trying to compile the project.

**Comment by UltraBurstXD** [comment]
The issue is due to 'core' module
