### ISSUE TITLE
Add Telugu translation

### ISSUE THREAD

**Issue by rajesh-v5** [trebleshot/android#180]
The current weblate project doesnt have a telugu language option for translation. It would be great if you could add it

**Comment by mubashir-rehman** [comment]
@rajesh-v5 Kindly wait for new updtae. It would be better because app has a lot of changes. Even if you contribute now, it won't be added to the app till next update.

**Comment by velitasali** [comment]
> The current weblate project doesnt have a telugu language option for translation. It would be great if you could add it

@mubashir-rehman is correct. It is better to wait for the announcement of the next update. Also, you can add a new language to the project :)

**Comment by velitasali** [comment]
@rajesh-v5 you can now add a new translation on Weblate. This link can be found in README.
