### ISSUE TITLE
WIP: release: 2.1

### ISSUE THREAD

**Issue by velitasali** [trebleshot/android#188]
## Planned

- [ ] Don't show a notification after a transfer finishes and the user is viewing transfer details or is  in the _Transfer History_ section
- [ ] Implement show files (open a file manager to view incoming transfer files)
- [ ] Check for accessibility issues and improve them
- [ ] Selections: select all & select none
- [ ] Keep the background service running if the user has picked the _Web Share_ option in the _Receive_ section

## Additional

- [ ] Ability to delete and rename contents
- [ ] _Try to_ re-enable failure on linting errors (currently disabled)
- [ ] Ability to change the save directory of a transfer (move the contents (received or being received but not running))
- [ ] Filtering (content-specific)
- [ ] Ability to select section titles (selects the contents under it)

## Low priority 

- [ ] App-wide search

**Comment by mubashir-rehman** [comment]
@velitasali feature to allow select folders in images category while sending on long press.

**Comment by mubashir-rehman** [comment]
@velitasali feature-request ability to send text messages but in a form that previous history is also visible. mainly for webshare.
Reason: i usually need to send different links and need them at random or multiple times. In v1.4.4 only one text message could be visible at a time. this doesn't allow multiple texts to be visible like a list of usernames and passwords on one singal page. i used to copy one username then send and then copy passowrd and send and the if needed again copy the first username and send.
