### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by subins2000** [trebleshot/android#38]
It would be great if there's documentation on how TrebleShot sending works. I am interested in developing a desktop app for TrebleShot ? It would be great if there's docs on how sending, discovering and receiving works.

**Comment by velitasali** [comment]
@subins2000 I will try to do my best. I really have a little time to work on the project. On the other hand implementing this class https://github.com/genonbeta/TrebleShot/blob/master/app/src/main/java/com/genonbeta/CoolSocket/CoolSocket.java to the platform you will be working on would be a good start. This class does most of the task. It is also what creates the communication server. I can help you if you want on how it should be working.

**Comment by IamJithendra** [comment]
@velitasali Can You Make A Video That Shows How TrebleShot Actually Works Which Can Also Be Posted On PlayStore Which Can Engage New Users

**Comment by velitasali** [comment]
@IamJithendra Currently I have only a little time to work on the project, but I will try to do my best.

**Comment by velitasali** [comment]
TrebleShot now uses uprotocol (see #143), which may get a proper documentation. This project can now be seen as a implementation of uprotocol and doesn't require documentation as that would made little sense.
