### ISSUE TITLE
Show Estimated Time Available On The Transferring Screen

### ISSUE THREAD

**Issue by IamJithendra** [trebleshot/android#44]
Show The ETA On The File Sharing Layout As A Progress bar which May Help the users to Know that Without Looking the Notification Bar

**Comment by velitasali** [comment]
Hi @IamJithendra , 

The design of the app will change and the change is already planned but will be done possibly in the later releases. You can join the discussion on Google+ to see what is planned next (the link is in the front page),

Thanks

**Comment by EmmanuelMess** [comment]
> The design of the app will change and the change is already planned but will be done possibly in the later releases.

Has this already been done?

> You can join the discussion on Google+ to see what is planned next (the link is in the front page),

It seems that the group was closed...

**Comment by velitasali** [comment]
> Has this already been done?
Nope. I guess I missed this. I mean there is progress bar, but it does not say estimated time.
> It seems that the group was closed...
Yes, there is only Telegram group now. https://t.me/trebleshot
