### ISSUE TITLE
Selected files are Unselected on Rotating the Screen In Trebleshot

### ISSUE THREAD

**Issue by neupanedipen** [trebleshot/android#46]
#### Expected behavior
When you select some files to share and then rotate the screen, the files should be shown selected in the rotated screen.<br>

#### Actual behavior
But when you select some files and then rotate the screen then the files will be unselected in Trebleshot and you'll have to select the files again to share them.<br>

#### How to reproduce
1. Download Trebleshot android app from Playstore.<br>
2. Launch it.<br>
3. Select some files to share .<br>![](https://s19.postimg.org/heat4atsj/Screenshot_20180401-000032.png)
4. Switch the orientation of your screen to landscape mode and rotate the screen.<br>
All the selected files will be unselected and you&apos;ll have to select them again to share the files.<br>
This bug is reported in Samsung Galaxy J5 Android 6.0.1 and in app version 1.2.5.12 .<br>

* App Version : 1.2.5.12 <br>![](https://s19.postimg.org/fl3b2i6g3/20180331_234802.png)
* Operating system: Android 6.0.1<br>![](https://s19.postimg.org/kxngrknmb/20180323_151702.png)

#### Recording Of The Bug
Here's the recording of the bug.<br>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/Cl7iVWszYcU" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@neupanedipen/selected-files-are-unselected-on-rotating-the-screen-in-trebleshot">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by kunalukey32** [comment]
Add in the manifest `<activity android:name=".YourActivity"
    android:screenOrientation="portrait"/>`
might be temporary solution 😉

**Comment by velitasali** [comment]
@kunalukey32 It will also make impossible to rotate the screen. A better solution is when selection is active, disabling the automatic rotation temporarily. I was also thinking about putting the selection into the database and retrieving them whenever the activity is recreated.

**Comment by rcs10** [comment]
@velitasali its because everytime theres a configuration change, activites get destroyed and recreated, fixed this issue ,can you review it?

**Comment by SweetD3v** [comment]
Simply add - android:configChanges="orientation|screenSize" in <activity android:name=".activity.HomeActivity"/>

**Comment by SweetD3v** [comment]
Simply add - android:configChanges="orientation|screenSize" in HomeActivity's manifest declaration.

**Comment by velitasali** [comment]
https://github.com/trebleshot/android/commit/a51f751087f1a6c469a36014b5004d614ffa063a and other related commits have resolved this problem.
