### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [trebleshot/android#50]
Good day ! this will be my propose design for TrebleShot Project

![proposal](https://user-images.githubusercontent.com/37318022/39660797-e32fe144-5078-11e8-90b8-31dbc5522e13.png)

I am open for any suggestions

**Comment by comradekingu** [comment]
I think there is a specific mention in the Material design guidelines about doing paper with a fold on it.

How about instead making the two papers (or similar) the icon?

**Comment by loydjayme25** [comment]
sorry, i don't get it sir. can you please explain it clearer ? so that i can make a design that fits to your project. Thanks !

**Comment by comradekingu** [comment]
It is not my decision to make, but this is what I meant.

![icondocuments](https://user-images.githubusercontent.com/13802408/40589509-ac1e4e48-61ee-11e8-929d-e152579cc219.png)

The fundamental problem here is that it isn't specific to TrebleShot, and also it is too limited.

**Comment by loydjayme25** [comment]
okay sir, ill make similar design with that one. what is your prefer sizes ? and the colors ?

**Comment by loydjayme25** [comment]
![new](https://user-images.githubusercontent.com/37318022/41269128-2eb19b6e-6e36-11e8-8ad9-0d0c5c3418b1.png)

@comradekingu  hello sir , sorry for a late response.

**Comment by comradekingu** [comment]
@loydjayme25
https://material.io/design/iconography/#
http://materialdesignblog.com/why-material-never-bends-or-folds/

Whatever the case with folding, it seems drop shadows and gradients are missing. To me it seems like paper has thickness too.

However, none of that makes it interesting, though you could learn from experimenting with it. "Scoring" might have some interesting qualities, it is limited to centerline horizontal and vertical axis. Though this might break with the perception of it being paper?

Pay attention to the rounding, your paper outline is, whereas the text isn't.
You are relying on two features, text and folding, to convey "paper", when it could be one.

Also, the colourchoice make it seem like it is either a cast-shadow from the wrong direction, or that the colours convey something (that I am missing)

Look at the design manual for darker and lighter shadowing in terms of direction.

The backdrop is out of alignment, the two papers are situated leftwards.
