### ISSUE TITLE
Add connect to pc option and shear in group option to trebleshot app.

### ISSUE THREAD

**Issue by pzdawood** [trebleshot/android#91]
***proposal***
My suggestion is to add the connect to PC option through which we can send files to PC and shear in group bottton through which we can send files in group to trebleshot app.
***Examples***
After adding the connect to pc botton option the app looks like this
![PicsArt_05-21-11 37 13](https://user-images.githubusercontent.com/38599784/58074676-77303d00-7bc3-11e9-8cd1-0f1d801b4f9c.png)
After adding the shear in group the looks looks like this
![PicsArt_05-21-11 42 09](https://user-images.githubusercontent.com/38599784/58074731-962ecf00-7bc3-11e9-9fee-57af2f3ae989.png)
After adding both these options
![PicsArt_05-21-11 38 41](https://user-images.githubusercontent.com/38599784/58074771-a8107200-7bc3-11e9-831d-19b509b0bde7.png)
The app that has both these options is shearit which is commonly used 
![Screenshot_2019-05-21-12-27-08-695_com lenovo anyshare gps](https://user-images.githubusercontent.com/38599784/58074896-f6257580-7bc3-11e9-855a-30883dee8c07.png)
***Benefits of both these options***
1. The benefit of shear in group option is that when we need  to shear any file to many people we have to send the file to people one by one of we have ***shear in group*** option we can make the group of all these people and send the file in the group. This option leads to reduce the wastage of time and quick shear to many people.
2. The Benefit of connect to pc option is that when we have shear any document or file from your mobile phone  to pc this option gives us that advantage.we have to download the the trebleshot app to both the pc and computer and then shear any file through this.

**Comment by velitasali** [comment]
Hi,

 Sending the same group of files with different people is already possible. For the second suggestion, I should say it is too early for that. The PC version is still in alpha stage.

Thanks.

**Comment by pzdawood** [comment]
Yes sir

**Comment by fazlerabbi37** [comment]
@velitasali it would be great if we had some sort of documentation that said there is PC version. Maybe in README or maybe in the FAQ. If you want I would be happy to send a PR with two lines pointing to the PC repo.

**Comment by velitasali** [comment]
@fazlerabbi37 yes you can do that. You should use the 'dev' branch.

**Comment by fazlerabbi37** [comment]
where do you suggest I should put it? README or FAQ? @velitasali

**Comment by velitasali** [comment]
@fazlerabbi37 to the top of the README file, maybe

**Comment by fazlerabbi37** [comment]
> @fazlerabbi37 to the top of the README file, maybe

done. :smile:
